CREATE TABLE "users"(
  id INTEGER NOT NULL UNIQUE,
  "username" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "rol" TEXT NOT NULL,
  PRIMARY KEY("id" AUTOINCREMENT)
)

CREATE TABLE ventas(
  id INTEGER NOT NULL UNIQUE,
  cliente TEXT NOT NULL,
  fecha DATETIME NOT NULL,
  valor INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE inventario(
  id INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  cantidad INTEGER NOT NULL,
  valor INTEGER NOT NULL,
  PRIMARY KEY("id" AUTOINCREMENT)
);
